version: '2' #docker-composeのバージョンを指定
services:
    semirevel:
        build: . #Dockerfileをビルド
        volumes:
          - "./:/go/src/SemiRevel"
        ports:
            - "9090:9000" #ポート9000番の開放
        command: revel run SemiRevel #docker-compose up の際にアプリケーション実行

networks:
  default:
    external:
      name: onyx
