version: '2' #docker-composeのバージョンを指定
services:
    db:
        image: mysql:5.7 #mysql5.7が準備されているimageを指定
        ports:
            - "13306:3306" # <-これがないと外からアクセス出来ない
        expose:
            - 13306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
           MYSQL_ROOT_PASSWORD: root #rootのパスワード
           MYSQL_DATABASE: semirevel #revelデータベースの作成
           MYSQL_USER: revel #revelユーザの作成
           MYSQL_PASSWORD: revel #revelユーザのパスワード
        volumes:
            - "./mysql:/docker-entrypoint-initdb.d"
    web:
        build: . #Dockerfileをビルド
        volumes:
          - "./:/go/src/SemiRevel"
        ports:
            - "9090:9000" #ポート9000番の開放
        links:
            - "db:mysql" #dbとつなげる
        command: revel run SemiRevel #docker-compose up の際にアプリケーション実行
